keypoints:
  - wrist
  - thumb_cmc
  - thumb_mcp
  - thumb_ip
  - thumb_tip
  - index_finger_mcp
  - index_finger_pip
  - index_finger_dip
  - index_finger_tip
  - middle_finger_mcp
  - middle_finger_pip
  - middle_finger_dip
  - middle_finger_tip
  - ring_finger_mcp
  - ring_finger_pip
  - ring_finger_dip
  - ring_finger_tip
  - little_finger_mcp
  - little_finger_pip
  - little_finger_dip
  - little_finger_tip